import js from "@eslint/js";
import pluginReact from "eslint-plugin-react";
import globals from "globals";
import tseslint from "typescript-eslint";

export default [
  {
    files: ["**/*.{js,mjs,cjs,ts,mts,cts,jsx,tsx}"],
    languageOptions: {
      globals: {
        ...globals.browser,
        ...globals.node,
      },
    },
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    files: ["**/*.{jsx,tsx}"],
    ...pluginReact.configs.flat.recommended,
    settings: {
      react: {
        version: "detect",
      },
    },
    rules: {
      "react/react-in-jsx-scope": "off", // Not needed in React 17+
      "react/prop-types": "off", // Using TypeScript for prop validation
    },
  },
  {
    files: ["**/*.{ts,tsx}"],
    rules: {
      "@typescript-eslint/no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_" },
      ],
      "@typescript-eslint/no-explicit-any": "warn",
      "@typescript-eslint/no-var-requires": "off", // Allow require() in Node.js files
    },
  },
  {
    files: ["functions/**/*.ts"],
    languageOptions: {
      globals: {
        ...globals.node,
        // Cloudflare Workers globals
        fetch: "readonly",
        Request: "readonly",
        Response: "readonly",
        URL: "readonly",
        Headers: "readonly",
        crypto: "readonly",
        WebSocket: "readonly",
        WebSocketPair: "readonly",
        setTimeout: "readonly",
        clearTimeout: "readonly",
        setInterval: "readonly",
        clearInterval: "readonly",
        atob: "readonly",
        btoa: "readonly",
      },
    },
  },
  {
    ignores: [
      "dist/**",
      "node_modules/**",
      ".wrangler/**",
      "coverage/**",
      "*.min.js",
      "build/**",
      ".vscode/**",
      ".DS_Store",
      "Thumbs.db",
      "*.log",
      "npm-debug.log*",
      "yarn-debug.log*",
      "yarn-error.log*",
      ".nyc_output/",
      "*.tmp",
      "*.temp",
      "worker-configuration.d.ts", // Generated by wrangler
      "functions/worker-configuration.d.ts", // Generated by wrangler
      "**/*.json", // JSON files don't need linting
      "**/*.jsonc", // JSONC files don't need linting
    ],
  },
];
